### ISSUE TITLE
Replace bitcoin_witness with rust-miniscript

### ISSUE THREAD

**Issue by D4nte** [comit-network/blockchain-contracts#23]
## Problem

We have a hand-rolled implementation for signing our Bitcoin HTLC.
This harms interoperability with other wallets and limits the usecases of COMIT.
This would also allow us to clean up some code (old `bitcoin_witness` crate).

## Goal

Use miniscript because it is a standardized way for doing contracts on Bitcoin.
It will also allow us to untie the library component of COMIT from cnd.

## Recommendation (copied from a previous comment)

In `blockchain_contracts`:
1. We would have to construct the HTLC from a miniscript instead of the current, serialized bytecode. A miniscript can be obtained by compiling a policy. Here is an example miniscript: `c:or_i(and_v(v:sha256(0000000000000000000000000000000000000000000000000000000000000001),pk_h(A)),and_v(after(1000),pk_h(B)))`
When picking up this issue, it is probably best to start from scratch with a policy.
2. Change the `BitcoinHtlc` to not sign transactions anymore. Instead, we should return the miniscript that we used to create the BitcoinHtlc.
3. Separately, we should provide functionality that allows one to consume this miniscript and given the necessary data, signs a transaction for you.
Most importantly though, this should be an optional feature so that users of `blockchain-contracts` are free to do the signing themselves or just pass the miniscript on to other clients.

In `cnd`:
We would have to re-work how `SpendOutput` is designed but basically, we just need to use the abstractions provided by `blockchain-contracts`. `blockchain-contracts` should provide everything so that we only need to put in:

- the secret
- the relevant keys
- the outpoint of the htlc
- the fee

Note: Make sure to use miniscript's fee estimation instead of hand rolling something!

**Comment by bonomat** [comment]
@thomaseizinger : can you please refine this ticket so that everyone can pick it up?

**Comment by D4nte** [comment]
This is blocked on:
- Removing rust-bitcoin-rpc
- Releasing once with minor API change (stopped using web3/rust-bitcoin types in favor of byte arrays)

@thomaseizinger to create all issues and assign dependencies

**Comment by thomaseizinger** [comment]
Make sure to use miniscript's fee estimation instead of hand rolling something!
