### ISSUE TITLE
Replace web3 with clarity and custom web3 client

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/blockchain-contracts#24]
## Problem

Web3 and its transitive dependencies are unergonomic, bulky and overall pretty painful.
We need to get rid them.

## Goal

Easy to consume and maintain code.

## The way forward

Clarity provides a fairly rich and yet lightweight low-level Ethereum interface: https://github.com/althea-net/clarity

It gives us stuff like an `Address` type and transaction signing.

We only use a handful of RPC calls, those can easily be re-created with a small client that has exactly the interface we need.

**Comment by D4nte** [comment]
@thomaseizinger do we still want that?

**Comment by thomaseizinger** [comment]
This, we can greatly simplify the tests in this repository if we don't use web3.
