### ISSUE TITLE
Understand Ethereum gas limits

### ISSUE THREAD

**Issue by D4nte** [comit-network/blockchain-contracts#52]
## Problem

We provide gas limit recommendation for ERC20 and Ether contracts interactions.
These recommendations are coming from the actual gas usage during the tests run:

https://github.com/comit-network/blockchain-contracts/blob/82cf33c0d01e445f2bd05bf3eb32a0143e672ab5/src/ethereum/rfc003/ether_htlc.rs#L39

Except for https://github.com/comit-network/blockchain-contracts/blob/82cf33c0d01e445f2bd05bf3eb32a0143e672ab5/src/ethereum/rfc003/erc20_htlc.rs#L56 which comes from comit-rs e2e tests.

As you can see, the actual gas usage in comments is actually way lower than the recommendation. This is because when the recommendation is decreased from 100,000 to 50,000 then the Ethereum transaction fails due to `out of gas`.

We don't know why.

## Goal

Be able to justify the gas limit recommendations and explain why we recommend 100,000 when actually the max usage is 30,000.

### A. Get a transaction trace from dev network. 

You can use https://github.com/comit-network/comit-rs/blob/master/api_tests/e2e/rfc003/eth_btc/ignore_fail_eth_transactions.ts
1. Put a very high gas limit value in `fundLowGas` (rename to `fundWithInsufficientGas`) and run the test with `--keep-on-failure` to have parity still running after test failure. The test will fail because `fundLowGas` checks that the transaction is failed. If the transaction is successful because there is enough gas, an exception is thrown making the test fail.
2. Check test logs to grab txid, get gas consumption from parity node
3. Readjust the gas limit to be just above the gas consumption, As per the assumptions of this issue, this should fail. Grab the trace, look at it, get @yosriady's help

### B. Get transaction from testnet

If you did not reach any conclusion from A. Play around in testnet and try to reach a conclusion.

Note: If the conclusion that parity is not behaving like testnet, then need to question whether our recommendations are valid, whether they are testable, we should swap eth node, etc.
Note: Gas prices are mentioned in the comments, these are not in scope.

**Comment by yosriady** [comment]
Sometimes Ethereum `out of gas` errors are actually execution errors. Do we have some of these transactions on viewable Etherscan?

Also, are gas prices configurable? Since HTLCs have an expiry date, we want to also recommend gas prices that lead to reasonable confirmation times.

**Comment by D4nte** [comment]
> > As you can see, the actual gas usage in comments is actually way lower than the recommendation. This is because when the recommendation is decreased from 100,000 to 50,000 then the Ethereum transaction fails due to out of gas.
> 
> Sometimes Ethereum `out of gas` errors are actually execution errors. Do we have some of these transactions on viewable Etherscan? They might be easier to debug.
> 
> --
> 
> Also, are [gas prices](https://ethgasstation.info/) configurable? Since HTLCs have an expiry date, we want to also recommend gas prices that lead to reasonable confirmation times.

Gas prices are handle by the SDK `EthereumWallet` so if the dev use their own wallet they can do whatever they want with it. Cnd does not recommend a gas price.

**Comment by D4nte** [comment]
> Sometimes Ethereum `out of gas` errors are actually execution errors. Do we have some of these transactions on viewable Etherscan? They might be easier to debug.

I can provide some parity trace stack but here we are talking about the exact same transactions (contract deploy or call contract).

- When gas limit is set to 100,000, it is successful and it consumes ~29000 gas.
- When gas is set to 50,000, out of gas error appears.

**Comment by yosriady** [comment]
> > Sometimes Ethereum `out of gas` errors are actually execution errors. Do we have some of these transactions on viewable Etherscan? They might be easier to debug.
> 
> I can provide some parity trace stack but here we are talking about the exact same transactions (contract deploy or call contract).
> 
> * When gas limit is set to 100,000, it is successful and it consumes ~29000 gas.
> * When gas is set to 50,000, out of gas error appears.

Yes, a stack trace would be helpful. If you can make the transactions on a testnet and provide the Etherscan links it will be even more helpful for debugging.

**Comment by yosriady** [comment]
> > Also, are [gas prices](https://ethgasstation.info/) configurable? Since HTLCs have an expiry date, we want to also recommend gas prices that lead to reasonable confirmation times.
> 
> Gas prices are handle by the SDK `EthereumWallet` so if the dev use their own wallet they can do whatever they want with it. Cnd does not recommend a gas price.

I see. Then in that case I think the dapp would have to be the one to recommend the values for the user. Metamask does the same thing:

![](https://metamask.zendesk.com/hc/article_attachments/360017326112/Screen_Shot_2018-12-11_at_9.11.13_PM.png)

**Comment by thomaseizinger** [comment]
> > Sometimes Ethereum `out of gas` errors are actually execution errors. Do we have some of these transactions on viewable Etherscan? They might be easier to debug.
> 
> I can provide some parity trace stack but here we are talking about the exact same transactions (contract deploy or call contract).
> 
>     * When gas limit is set to 100,000, it is successful and it consumes ~29000 gas.
> 
>     * When gas is set to 50,000, out of gas error appears.

Ethereum refunds you some of the gas for specific opcodes like `revert`. Maybe we are actually consuming more than 50k gas during the execution but some of it is credited back in the end, resulting in a lower overall cost.

**Comment by D4nte** [comment]
> > > Sometimes Ethereum `out of gas` errors are actually execution errors. Do we have some of these transactions on viewable Etherscan? They might be easier to debug.
> > 
> > 
> > I can provide some parity trace stack but here we are talking about the exact same transactions (contract deploy or call contract).
> > ```
> > * When gas limit is set to 100,000, it is successful and it consumes ~29000 gas.
> > 
> > * When gas is set to 50,000, out of gas error appears.
> > ```
> 
> Ethereum refunds you some of the gas for specific opcodes like `revert`. Maybe we are actually consuming more than 50k gas during the execution but some of it is credited back in the end, resulting in a lower overall cost.

Yes I assume it would be something like that, however I think it'd be good to understand to provide a more precise gas limit recommendation and not just one "that works".

**Comment by bonomat** [comment]
The used gas for happy path is lower than the recommendation as we get a _gas refund_ when calling selfdestruct. 

I can do a rough breakdown of the gas cost if that helps?

**Comment by bonomat** [comment]
# Deployment cost: 

## ETH HTLC Contract deployment cost

* CREATE: 32k 
* Normal tx fee: 21k 
* Transaction data: 311 bytes * 68 (roughly, ignoring deploy header) = 21k
* Contract size: 311 bytes * 200 (roughly, ignoring 0 bytes) = 62k
---- 
sum: 21+21+21+62=~136k (used 126450)

## ERC20 HTLC Contract deployment cost

* CREATE: 32k 
* Normal tx fee: 21k 
* Transaction data: 411 bytes * 68 (roughly, ignoring 0 bytes which would cost less) = 28k
* Contract size: 411 bytes * 200 (roughly, ignoring deploy header) = 82k
---- 
sum: 32+21+28+82=~163k (used 151220)

# Redeem cost: 

## ERC20 HTLC Redeem transaction
* Normal tx fee: 21k 
* Transaction data: 32 bytes * 68 = 2k
* Contract execution (roughly): 2+3+2+3+3+(3+3*32+32)+(9000+21000+2000)+(3*33)+3+3+10+(375+375*1+8*32+0)+(3+32)+10+(3+4)+(9000+21000+2000)+2-24000
---
Sum: ~41319 (used 29840) needed: 59740

----
Verified with 
`29840 + 24000` --> test failure ?
`29840 + 24000 + 5900` --> works -> the problem seems to be the last call to transfer the tokens where we need to pass in more gas. Who has the contract source of this? It could be that this function requires more gas to be passed into. We do something weird there - see here: 
https://github.com/comit-network/blockchain-contracts/blob/c77f4c35a25274b3ee0ca4780e076af0c15c01c8/src/bin/calculate_offsets/ethereum/rfc003/templates/erc20/contract.asm#L110

I did not want to recompile and try to adjust this but I think this evaluation is close enough.


## Ether HTLC Redeem transaction: 

* Normal tx fee: 21k 
* Transaction data: 32 bytes * 68 = 2k
* Contract execution (roughly): (lost my data :( )

--- 
Sum: ~54125 (used 31082)

----

Verified with 
`31082 + 23999` --> test failure
`31082 + 24000` --> test works

## Ether HTLC Refund: 

Did not investigate further

## ERC20 HTLC Refund: 

Did not investigate further

<details>
<summary>Cost annotated ERC20</summary>
```
{
    calldatasize 2
    iszero 3
    time has been reached
    check_expiry
    jumpi 10
    32
    calldatasize 2
    eq 3
    iszero 3
    invalid_secret
    jumpi 10
    calldatacopy(0, 0, 32) 3 + 3 *32 + 32
    call(72, 0x02, 0, 0, 32, 33, 32) 9000+21000+2000
    0x1000000000000000000000000000000000000000000000000000000000000001
    mload(33) 3*33
    eq 3
    and 3
    redeem
    jumpi 10
invalid_secret:
    mstore(0, "invalidSecret") 3*32
    revert(0, 32)

check_expiry:
    timestamp 2
    0x20000002
    lt 3
    refund
    jumpi 10
    mstore(0, "tooEarly") 3*32
    revert(0, 32)


redeem:
    log1(0, 32, "redeemed") 375 + 375 * 1 + 8 * 32 + 0 (mem_expansion_cost)
    mstore(32,0x3000000000000000000000000000000000000003) // redeem address 3*32
    finishTransferTokens
    jump 10 

refund:
    log1(0, 0, "refunded") 375 + 375 * 1 + 8 * 32 + 0 (mem_expansion_cost)
    mstore(32, 0x4000000000000000000000000000000000000004) // refund address 3*32
    finishTransferTokens
    jump 10

finishTransferTokens:
    mstore(0, 0xa9059cbb) // first 4bytes of keccak256("transfer(address,uint256)") 3*4
    mstore(64, 0x5000000000000000000000000000000000000000000000000000000000000005) 
    call(
      sub(gas,100000), 
      0x6000000000000000000000000000000000000006, // Token Contract address
      0,  // Ether to transfer
      28, // = 32-4
      68, // = 2*32+4
      96, // return location
      32  // return size
    ) (9000+21000+2000) --> roughly
    pop 2

    selfdestruct(mload(32)) -24000
}
```


</details>

Playground PR: https://github.com/comit-network/blockchain-contracts/pull/56

**Comment by bonomat** [comment]
Summary: 

We need to provide more gas than actually used as our contract frees up some gas by using `selfdestruct` and `revert`. Differently said: EVM executes every op_code sequentially, calculates the needed gas and verifies if enough gas was provided in the transaction. If not, it throws an error. 

Feel free to close this if this explanation is enough for you.

**Comment by D4nte** [comment]
@bonomat Sounds good. Thanks. Can you update the recommendations and comments accordingly in the code while it's still fresh?

**Comment by bonomat** [comment]
@D4nte : #56 was just a playground. 

Would you like to see the proposal (tests) in this PR being integrated? 
a) If so, I would rather create a ticket to do the work. I'm not happy with how it's solved right now
b) If not, do you _just_ want a code comment adding some details as it is right now in here: 
https://github.com/comit-network/blockchain-contracts/blob/3259a263337d01a746bec1b5c47a1c9aeb576d29/src/ethereum/rfc003/erc20_htlc.rs#L47-L51

**Comment by D4nte** [comment]
@bonomat I suggest we scope this issue to test the new gas recommendation with comit-rs tests and update the explanations.

**Comment by bonomat** [comment]
Replaced by #57
