### ISSUE TITLE
Use `revert` on failure in Ethereum HTLCs

### ISSUE THREAD

**Issue by D4nte** [comit-network/blockchain-contracts#8]
## Problem

It is hard for a developer to understand why the HTLC does not behave as expected in case of failure.

## Goal

Make it easier to understand why a call to the Ethereum HTLCs fail.

## Agreed Recommendation

Use `revert` and on failure paths. See comit-network/spikes#37 for more details.

Tasks:
- [x] Update Ether HTLC to `revert` with a reason instead of `return`. The transaction must be marked as `Failed` if secret is incorrect or attempt to refund is made and time is not yet expired. 
- [x] Update ERC20 HTLC to `revert` as above.
- [x] Create RFC issue to update the 2 RFCs (HTLC Ether and ERC20)

**Comment by bonomat** [comment]
Not that it is that important, but, afaik it is best practice to use capitalization for events to not confuse event messages with function calls, i.e. i.e. use `TooEarly()` and `WrongSecret()` instead.

**Comment by da-kami** [comment]
Would be great to add the problem and the goal to this ticket to make it more understandable.

**Comment by D4nte** [comment]
> Not that it is that important, but, afaik it is best practice to use capitalization for events to not confuse event messages with function calls, i.e. i.e. use `TooEarly()` and `WrongSecret()` instead.

Just correct the description please.

**Comment by bonomat** [comment]
TIL: 

`revert` reverts contract changes. Among others, `events` are contract changes. Hence, the combination of `log MSG` + `revert` does not make sense :D

**Comment by bonomat** [comment]
# Mini spike: 

`revert` vs `events`:

## `revert`
The `revert` opcode will stop the execution, roll back all state changes done so far and provides an address where one could store an error message. 

* `+` Transaction shows up as failed, which _feels_ logical from the send point of view. 
* `+` Left over gas is returned
* `+` Error code (0) is returned to the user
* "+" Error message can be retrieved from another contract
* `-` memory cost: revert lets you return a memory address, meaning we need to store something in that memory first. 
* `-` it is not trivial to get the error message from the call, i.e. the sender does not receive the error message by default in the transaction receipt but has to go back and one would need to do some web3 acrobatic moves to retrieve it: 
https://gist.github.com/gluk64/fdea559472d957f1138ed93bcbc6f78a
or here in this PR: https://github.com/comit-network/blockchain-contracts/blob/781d42317c506cdfc79c329e0ec30eb914be5d89/tests/parity_client/mod.rs#L192-L223

## `events`
* `+` can be retrieved easily
* `+` clear distinguishable log messages
* `+` can be read easily from a thirdparty (or counter party) through web3.getTransactionReceipt  - (compared to the revert log
* `-` cannot be read from another contract
* `-` don't work in combination with `revert`

## Conclusion :

I opted for going with `events` + `return` as this allows us to retrieve the reason easily by just looking at the transaction receipt.
Yos also mentioned that returning a value would make our contracts _DeFi_ ready which is a plus :)

Checkout this PR: https://github.com/comit-network/blockchain-contracts/pull/35
