### ISSUE TITLE
Clean-up test harness

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/blockchain-contracts#9]
## Problem

As part of doing #4, a fair amount of duplication was created in the test-harness.

## Goal

This crate contains code that is critical to COMIT. Not only the actual production code, but also the testcode should be easy to understand, verify and maintain.

## Recommendation

- Cut down on the number of dependencies
- Only take trust-worthy dependencies

Major painpoints:
- ~`ethereum_helper::ToEthereumAddress`~ https://github.com/comit-network/blockchain-contracts/issues/24
- ~`ethereum_helper::InMemoryWallet`~ https://github.com/comit-network/blockchain-contracts/issues/24
- `bitcoin_helper::RegtestHelperClient`

**Comment by thomaseizinger** [comment]
Possibly helpful for the ethereum stuff: https://docs.rs/clarity/0.1.20/clarity

**Comment by bonomat** [comment]
Not now and stale for a while --> closed.

**Comment by thomaseizinger** [comment]
We should really do this, there is quite some frustrating mess in here.

**Comment by thomaseizinger** [comment]
Partially replaced by https://github.com/comit-network/blockchain-contracts/issues/24.
